// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/coupons">> = Specific
  const handler = {} as typeof import("../../app/manager/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/menus/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/menus/availability">> = Specific
  const handler = {} as typeof import("../../app/manager/menus/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/menus/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/menus/categories">> = Specific
  const handler = {} as typeof import("../../app/manager/menus/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/menus/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/menus/items">> = Specific
  const handler = {} as typeof import("../../app/manager/menus/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/menus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/menus">> = Specific
  const handler = {} as typeof import("../../app/manager/menus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/orders">> = Specific
  const handler = {} as typeof import("../../app/manager/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager">> = Specific
  const handler = {} as typeof import("../../app/manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/recommendations">> = Specific
  const handler = {} as typeof import("../../app/manager/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/settings/location-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/settings/location-settings">> = Specific
  const handler = {} as typeof import("../../app/manager/settings/location-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/settings">> = Specific
  const handler = {} as typeof import("../../app/manager/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/settings/printers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/settings/printers">> = Specific
  const handler = {} as typeof import("../../app/manager/settings/printers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/settings/role-permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/settings/role-permissions">> = Specific
  const handler = {} as typeof import("../../app/manager/settings/role-permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/settings/system-menus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/settings/system-menus">> = Specific
  const handler = {} as typeof import("../../app/manager/settings/system-menus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/settings/user-permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/settings/user-permissions">> = Specific
  const handler = {} as typeof import("../../app/manager/settings/user-permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/stores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/stores">> = Specific
  const handler = {} as typeof import("../../app/manager/stores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/users">> = Specific
  const handler = {} as typeof import("../../app/manager/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/users/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/users/roles">> = Specific
  const handler = {} as typeof import("../../app/manager/users/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../app/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order">> = Specific
  const handler = {} as typeof import("../../app/order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rewards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rewards">> = Specific
  const handler = {} as typeof import("../../app/rewards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google">> = Specific
  const handler = {} as typeof import("../../app/api/auth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/business-hours/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/business-hours/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/business-hours/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/business-hours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/business-hours">> = Specific
  const handler = {} as typeof import("../../app/api/business-hours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/[cartId]/coupon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/[cartId]/coupon">> = Specific
  const handler = {} as typeof import("../../app/api/cart/[cartId]/coupon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/[cartId]/items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/[cartId]/items/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/api/cart/[cartId]/items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/[cartId]/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/[cartId]/items">> = Specific
  const handler = {} as typeof import("../../app/api/cart/[cartId]/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/[cartId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/[cartId]">> = Specific
  const handler = {} as typeof import("../../app/api/cart/[cartId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart">> = Specific
  const handler = {} as typeof import("../../app/api/cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locale">> = Specific
  const handler = {} as typeof import("../../app/api/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/locations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locations/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/current">> = Specific
  const handler = {} as typeof import("../../app/api/locations/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locations/resolve-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/resolve-id">> = Specific
  const handler = {} as typeof import("../../app/api/locations/resolve-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations">> = Specific
  const handler = {} as typeof import("../../app/api/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/business-hours/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/business-hours/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/business-hours/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/business-hours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/business-hours">> = Specific
  const handler = {} as typeof import("../../app/api/manager/business-hours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/business-settings/effective/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/business-settings/effective">> = Specific
  const handler = {} as typeof import("../../app/api/manager/business-settings/effective/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/business-settings/location/[locationId]/[settingKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/business-settings/location/[locationId]/[settingKey]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/business-settings/location/[locationId]/[settingKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/business-settings/location/[locationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/business-settings/location/[locationId]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/business-settings/location/[locationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/business-settings/system/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/business-settings/system">> = Specific
  const handler = {} as typeof import("../../app/api/manager/business-settings/system/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/coupons/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/coupons/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/coupons/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/coupons/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/coupons/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/manager/coupons/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/coupons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/coupons">> = Specific
  const handler = {} as typeof import("../../app/api/manager/coupons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/location-menu-overrides/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/location-menu-overrides/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/location-menu-overrides/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/location-menu-overrides/by-target/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/location-menu-overrides/by-target">> = Specific
  const handler = {} as typeof import("../../app/api/manager/location-menu-overrides/by-target/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/location-menu-overrides/item-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/location-menu-overrides/item-image">> = Specific
  const handler = {} as typeof import("../../app/api/manager/location-menu-overrides/item-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/location-menu-overrides/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/location-menu-overrides">> = Specific
  const handler = {} as typeof import("../../app/api/manager/location-menu-overrides/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/location-settings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/location-settings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/location-settings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/location-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/location-settings">> = Specific
  const handler = {} as typeof import("../../app/api/manager/location-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/locations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/locations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/locations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/locations">> = Specific
  const handler = {} as typeof import("../../app/api/manager/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-catalog">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-categories">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-item-images/[id]/picture/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-item-images/[id]/picture">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-item-images/[id]/picture/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-item-images/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-item-images/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-item-images/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-item-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-item-images">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-item-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-item-images/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-item-images/upload">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-item-images/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-items/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-items">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-recommendations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-recommendations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-recommendations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-recommendations/location-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-recommendations/location-visibility">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-recommendations/location-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/menu-recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/menu-recommendations">> = Specific
  const handler = {} as typeof import("../../app/api/manager/menu-recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/permission-codes/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/permission-codes/[code]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/permission-codes/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/permission-codes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/permission-codes">> = Specific
  const handler = {} as typeof import("../../app/api/manager/permission-codes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/printing/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/printing/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/printing/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/role-menus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/role-menus">> = Specific
  const handler = {} as typeof import("../../app/api/manager/role-menus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/roles/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/roles">> = Specific
  const handler = {} as typeof import("../../app/api/manager/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/system-menus/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/system-menus/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/system-menus/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/system-menus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/system-menus">> = Specific
  const handler = {} as typeof import("../../app/api/manager/system-menus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/system-settings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/system-settings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/system-settings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/system-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/system-settings">> = Specific
  const handler = {} as typeof import("../../app/api/manager/system-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/user-permissions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/user-permissions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/user-permissions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/user-permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/user-permissions">> = Specific
  const handler = {} as typeof import("../../app/api/manager/user-permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/user-roles/[userId]/[roleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/user-roles/[userId]/[roleId]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/user-roles/[userId]/[roleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/user-roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/user-roles">> = Specific
  const handler = {} as typeof import("../../app/api/manager/user-roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/manager/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manager/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/users">> = Specific
  const handler = {} as typeof import("../../app/api/manager/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/default-location/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/default-location">> = Specific
  const handler = {} as typeof import("../../app/api/me/default-location/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/frequent-menu-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/frequent-menu-items">> = Specific
  const handler = {} as typeof import("../../app/api/me/frequent-menu-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/profile">> = Specific
  const handler = {} as typeof import("../../app/api/me/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/rewards/redemption-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/rewards/redemption-status">> = Specific
  const handler = {} as typeof import("../../app/api/me/rewards/redemption-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/rewards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/rewards">> = Specific
  const handler = {} as typeof import("../../app/api/me/rewards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/rewards/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/rewards/transactions">> = Specific
  const handler = {} as typeof import("../../app/api/me/rewards/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/menu-catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu-catalog">> = Specific
  const handler = {} as typeof import("../../app/api/menu-catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/menu-items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu-items/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/menu-items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/menu-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu-items">> = Specific
  const handler = {} as typeof import("../../app/api/menu-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/menu-recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu-recommendations">> = Specific
  const handler = {} as typeof import("../../app/api/menu-recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/refunds">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/orders/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/redemption-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/redemption-preview">> = Specific
  const handler = {} as typeof import("../../app/api/orders/redemption-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/stripe/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/stripe/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/payments/stripe/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/stripe/payment-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/stripe/payment-intent">> = Specific
  const handler = {} as typeof import("../../app/api/payments/stripe/payment-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/payments/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/print-agent/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print-agent/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/print-agent/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manager/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/manager">> = Specific
  const handler = {} as typeof import("../../app/manager/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
