import type { ManagerDashboard, ManagerMenu, ManagerPermission, ManagerRoleAccess, ManagerUser } from "@/lib/manager-types";

export const managerPermissions: ManagerPermission[] = [
  { code: "DASHBOARD_VIEW", description: "View manager dashboard metrics", group: "Dashboard", scope: "store" },
  { code: "STORE_VIEW", description: "View store details and hours", group: "Stores", scope: "store" },
  { code: "STORE_EDIT", description: "Edit store details and hours", group: "Stores", scope: "store" },
  { code: "USER_VIEW", description: "View customers and staff", group: "Users", scope: "store" },
  { code: "USER_CREATE", description: "Invite staff users", group: "Users", scope: "store" },
  { code: "USER_EDIT", description: "Edit users and staff assignments", group: "Users", scope: "store" },
  { code: "USER_ROLE_ASSIGN", description: "Assign roles and permissions", group: "Users", scope: "global" },
  { code: "MENU_VIEW", description: "View categories, items, options, and images", group: "Menus", scope: "store" },
  { code: "MENU_CREATE", description: "Create menu categories and items", group: "Menus", scope: "store" },
  { code: "MENU_EDIT", description: "Edit menu categories and items", group: "Menus", scope: "store" },
  { code: "MENU_AVAILABILITY_EDIT", description: "Change temporary menu item availability", group: "Menus", scope: "store" },
  { code: "ORDER_VIEW", description: "View orders", group: "Orders", scope: "store" },
  { code: "ORDER_STATUS_EDIT", description: "Update order status", group: "Orders", scope: "store" },
  { code: "ORDER_CANCEL", description: "Cancel orders", group: "Orders", scope: "store" },
  { code: "REWARD_VIEW", description: "View reward ledgers and wallets", group: "Rewards", scope: "store" },
  { code: "REWARD_ADJUST", description: "Manually adjust reward points", group: "Rewards", scope: "store" },
  { code: "PAYMENT_VIEW", description: "View payment transactions and refunds", group: "Payments", scope: "store" },
  { code: "PAYMENT_REFUND", description: "Issue refunds", group: "Payments", scope: "global" },
  { code: "NOTIFICATION_VIEW", description: "View notification logs and templates", group: "Notifications", scope: "store" },
  { code: "NOTIFICATION_EDIT", description: "Edit notification templates", group: "Notifications", scope: "global" },
  { code: "AUDIT_LOG_VIEW", description: "View audit logs", group: "Audit", scope: "store" },
  { code: "SETTING_VIEW", description: "View system settings", group: "Settings", scope: "global" },
  { code: "SETTING_EDIT", description: "Edit system settings", group: "Settings", scope: "global" },
];

export const managerMenus: ManagerMenu[] = [
  { id: "dashboard", name: "Dashboard", code: "MANAGER_DASHBOARD", path: "/manager", icon: "LayoutDashboard", sortOrder: 10, permission: "DASHBOARD_VIEW" },
  {
    id: "stores",
    name: "Stores",
    code: "MANAGER_STORES",
    path: "/manager/stores",
    icon: "Store",
    sortOrder: 20,
    permission: "STORE_VIEW",
    children: [
      { id: "store-details", name: "Store Details", code: "MANAGER_STORE_DETAILS", path: "/manager/stores/details", icon: "Store", sortOrder: 10, permission: "STORE_VIEW" },
      { id: "store-hours", name: "Store Hours", code: "MANAGER_STORE_HOURS", path: "/manager/stores/hours", icon: "Clock3", sortOrder: 20, permission: "STORE_EDIT" },
    ],
  },
  {
    id: "users",
    name: "Users",
    code: "MANAGER_USERS",
    path: "/manager/users",
    icon: "Users",
    sortOrder: 30,
    permission: "USER_VIEW",
    children: [
      { id: "customers", name: "Customers", code: "MANAGER_CUSTOMERS", path: "/manager/users", icon: "UserRound", sortOrder: 10, permission: "USER_VIEW" },
      { id: "staff", name: "Staff Members", code: "MANAGER_STAFF_MEMBERS", path: "/manager/users?type=staff", icon: "Users", sortOrder: 20, permission: "USER_VIEW" },
      { id: "invites", name: "Staff Invites", code: "MANAGER_STAFF_INVITES", path: "/manager/users?type=invites", icon: "MailPlus", sortOrder: 30, permission: "USER_CREATE" },
      { id: "roles", name: "Roles & Permissions", code: "MANAGER_ROLES_PERMISSIONS", path: "/manager/users/roles", icon: "ShieldCheck", sortOrder: 40, permission: "USER_ROLE_ASSIGN" },
    ],
  },
  {
    id: "menus",
    name: "Menus",
    code: "MANAGER_MENUS",
    path: "/manager/menus",
    icon: "Utensils",
    sortOrder: 40,
    permission: "MENU_VIEW",
    children: [
      { id: "categories", name: "Categories", code: "MANAGER_MENU_CATEGORIES", path: "/manager/menus/categories", icon: "Folders", sortOrder: 10, permission: "MENU_VIEW" },
      { id: "items", name: "Items", code: "MANAGER_MENU_ITEMS", path: "/manager/menus/items", icon: "SquareLibrary", sortOrder: 20, permission: "MENU_EDIT" },
      { id: "availability", name: "Availability", code: "MANAGER_MENU_AVAILABILITY", path: "/manager/menus/availability", icon: "BadgeAlert", sortOrder: 50, permission: "MENU_AVAILABILITY_EDIT" },
    ],
  },
  { id: "orders", name: "Orders", code: "MANAGER_ORDERS", path: "/manager/orders", icon: "ClipboardList", sortOrder: 50, permission: "ORDER_VIEW" },
  { id: "rewards", name: "Rewards", code: "MANAGER_REWARDS", path: "/manager/rewards", icon: "BadgePercent", sortOrder: 60, permission: "REWARD_VIEW" },
  { id: "payments", name: "Payments", code: "MANAGER_PAYMENTS", path: "/manager/payments", icon: "CreditCard", sortOrder: 70, permission: "PAYMENT_VIEW" },
  { id: "notifications", name: "Notifications", code: "MANAGER_NOTIFICATIONS", path: "/manager/notifications", icon: "Bell", sortOrder: 80, permission: "NOTIFICATION_VIEW" },
  { id: "audit", name: "Audit Logs", code: "MANAGER_AUDIT_LOGS", path: "/manager/audit-logs", icon: "FileSearch", sortOrder: 90, permission: "AUDIT_LOG_VIEW" },
  {
    id: "settings",
    name: "Settings",
    code: "MANAGER_SETTINGS",
    path: "/manager/settings",
    icon: "Settings",
    sortOrder: 100,
    permission: "SETTING_VIEW",
    children: [
      {
        id: "system-menus",
        name: "System Menus",
        code: "MANAGER_SYSTEM_MENUS",
        path: "/manager/settings/system-menus",
        icon: "MenuSquare",
        sortOrder: 30,
        permission: "SETTING_VIEW",
      },
      {
        id: "location-settings",
        name: "Location Settings",
        code: "MANAGER_LOCATION_SETTINGS",
        path: "/manager/settings/location-settings",
        icon: "SlidersHorizontal",
        sortOrder: 40,
        permission: "SETTING_EDIT",
      },
      { id: "role-permissions", name: "Role Permissions", code: "MANAGER_ROLE_PERMISSIONS", path: "/manager/settings/role-permissions", icon: "ShieldCheck", sortOrder: 50, permission: "SETTING_EDIT" },
      { id: "user-permissions", name: "User Permissions", code: "MANAGER_USER_PERMISSIONS", path: "/manager/settings/user-permissions", icon: "ShieldUser", sortOrder: 60, permission: "USER_ROLE_ASSIGN" },
    ],
  },
];

export const managerRoleAccess: ManagerRoleAccess[] = [
  {
    role: "ROLE_ADMIN",
    label: "Admin",
    scope: "Global",
    description: "Owner or platform administrator with access to all stores, settings, menus, users, roles, and audit history.",
    menuCodes: managerMenus.flatMap((menu) => [menu.code, ...(menu.children?.map((child) => child.code) ?? [])]),
    permissionCodes: managerPermissions.map((permission) => permission.code),
  },
  {
    role: "ROLE_MANAGER",
    label: "Manager",
    scope: "Assigned store",
    description: "Store manager who operates their assigned location, invites staff, edits menus, and reviews local orders.",
    menuCodes: [
      "MANAGER_DASHBOARD",
      "MANAGER_STORES",
      "MANAGER_USERS",
      "MANAGER_STAFF_MEMBERS",
      "MANAGER_STAFF_INVITES",
      "MANAGER_ROLES_PERMISSIONS",
      "MANAGER_MENUS",
      "MANAGER_ORDERS",
      "MANAGER_REWARDS",
      "MANAGER_PAYMENTS",
      "MANAGER_NOTIFICATIONS",
      "MANAGER_AUDIT_LOGS",
      "MANAGER_SETTINGS",
    ],
    permissionCodes: [
      "DASHBOARD_VIEW",
      "STORE_VIEW",
      "STORE_EDIT",
      "USER_VIEW",
      "USER_CREATE",
      "USER_EDIT",
      "MENU_VIEW",
      "MENU_CREATE",
      "MENU_EDIT",
      "MENU_AVAILABILITY_EDIT",
      "ORDER_VIEW",
      "ORDER_STATUS_EDIT",
      "ORDER_CANCEL",
      "REWARD_VIEW",
      "PAYMENT_VIEW",
      "NOTIFICATION_VIEW",
      "AUDIT_LOG_VIEW",
      "SETTING_VIEW",
    ],
  },
  {
    role: "ROLE_STAFF",
    label: "Staff",
    scope: "Assigned store",
    description: "Front counter and kitchen staff access for day-to-day order handling and temporary item availability changes.",
    menuCodes: ["MANAGER_DASHBOARD", "MANAGER_MENUS", "MANAGER_ORDERS"],
    permissionCodes: ["DASHBOARD_VIEW", "MENU_VIEW", "MENU_AVAILABILITY_EDIT", "ORDER_VIEW", "ORDER_STATUS_EDIT"],
  },
];

export const managerUsers: ManagerUser[] = [
  {
    id: "usr_001",
    name: "Mika Tanaka",
    email: "owner@umikasushi.ca",
    phone: "416-555-0101",
    role: "ROLE_ADMIN",
    status: "ACTIVE",
    locationName: "All stores",
    points: 0,
    lastSeen: "Today, 8:12 AM",
    permissions: ["SETTING_EDIT", "USER_ROLE_ASSIGN", "PAYMENT_REFUND"],
  },
  {
    id: "usr_002",
    name: "Daniel Wong",
    email: "manager@umikasushi.ca",
    phone: "416-555-0134",
    role: "ROLE_MANAGER",
    status: "ACTIVE",
    locationName: "Toronto Main",
    points: 0,
    lastSeen: "Today, 7:46 AM",
    permissions: ["USER_CREATE", "MENU_EDIT", "ORDER_CANCEL"],
  },
  {
    id: "usr_003",
    name: "Sara Chen",
    email: "staff@umikasushi.ca",
    phone: "416-555-0199",
    role: "ROLE_STAFF",
    status: "ACTIVE",
    locationName: "Toronto Main",
    points: 0,
    lastSeen: "Yesterday, 6:25 PM",
    permissions: ["ORDER_STATUS_EDIT", "MENU_AVAILABILITY_EDIT"],
  },
  {
    id: "usr_004",
    name: "Amelia Park",
    email: "amelia@example.com",
    phone: "416-555-0157",
    role: "ROLE_CUSTOMER",
    status: "ACTIVE",
    locationName: "Customer account",
    points: 340,
    lastSeen: "Jun 23, 2026",
    permissions: [],
  },
  {
    id: "usr_005",
    name: "Leo Martin",
    email: "leo@example.com",
    role: "ROLE_CUSTOMER",
    status: "INVITED",
    locationName: "Staff invite pending",
    points: 0,
    lastSeen: "Invite sent today",
    permissions: [],
  },
];

export const managerDashboard: ManagerDashboard = {
  stats: [
    { label: "Open orders", value: "18", detail: "6 preparing, 4 ready for pickup" },
    { label: "Staff online", value: "7", detail: "Manager plus 6 staff across assigned stores" },
    { label: "Role changes", value: "3", detail: "Permissions updated in the last 24 hours" },
    { label: "Menu alerts", value: "5", detail: "Temporary sold-out overrides active" },
  ],
  alerts: [
    { label: "Staff invite expiring", severity: "warning", detail: "Leo Martin's invite expires in 18 hours." },
    { label: "Permission audit due", severity: "info", detail: "Review manager-level refund access this week." },
    { label: "System menus synced", severity: "success", detail: "Manager navigation matches the latest SQL seed." },
  ],
  activity: [
    { id: "act_001", actor: "Mika Tanaka", action: "Granted USER_ROLE_ASSIGN", target: "Daniel Wong", at: "8:04 AM" },
    { id: "act_002", actor: "Daniel Wong", action: "Sent staff invite", target: "Leo Martin", at: "7:58 AM" },
    { id: "act_003", actor: "Sara Chen", action: "Marked item unavailable", target: "Spicy Tuna Roll", at: "Yesterday" },
  ],
};
