import type { Locale } from "@/lib/i18n";

const en = {
  eyebrow: "Printer settings", title: "Receipt templates", description: "Set the receipt appearance and visible order details for each store. New paid orders use the saved template.",
  location: "Location", chooseLocation: "Choose a location", appearance: "Appearance", header: "Header text", headerPlaceholder: "Optional store or kitchen heading", footer: "Footer text", footerPlaceholder: "Optional message at the bottom", fontSize: "Text size", compact: "Compact", standard: "Standard", large: "Large",
  complete: "Complete order receipt", station: "Station receipt", customerPhone: "Customer phone", placedTime: "Placed time", itemPrices: "Item prices", subtotal: "Subtotal", discount: "Discount", tax: "Tax", tip: "Tip", orderTotal: "Whole order total", stationCount: "Station item quantity",
  preview: "Preview", previewHelp: "The preview shows the selected fields. Printed line wrapping may vary with item names.", order: "PICKUP · WHOLE ORDER", stationOrder: "PICKUP · SUSHI BAR", customer: "Alex Chen", phone: "416-555-0123", pickup: "Pickup: 6:30 PM", placed: "Placed: 6:02 PM", item: "2 × California Roll", note: "No sesame", thanks: "Footer text", save: "Save template", saved: "Receipt template saved. New orders will use it.", loading: "Loading…", error: "Could not load or save the receipt template.", denied: "You need location settings permission for this store.", auth: "Please sign in again.", invalid: "Check the template fields and try again.",
};
const zh: typeof en = {
  eyebrow:"打印机设置",title:"小票模板",description:"为每家门店设置小票外观和显示的订单信息。新付款订单将使用已保存的模板。",location:"门店",chooseLocation:"选择门店",appearance:"外观",header:"顶部文字",headerPlaceholder:"可选的门店或厨房标题",footer:"底部文字",footerPlaceholder:"可选的底部信息",fontSize:"字体大小",compact:"紧凑",standard:"标准",large:"大号",complete:"整单小票",station:"档口小票",customerPhone:"顾客电话",placedTime:"下单时间",itemPrices:"菜品价格",subtotal:"小计",discount:"折扣",tax:"税费",tip:"小费",orderTotal:"整单总价",stationCount:"档口菜品数量",preview:"预览",previewHelp:"预览会显示所选内容。实际打印换行可能随菜品名称而变化。",order:"自取 · 整单",stationOrder:"自取 · 寿司吧",customer:"Alex Chen",phone:"416-555-0123",pickup:"取餐：下午 6:30",placed:"下单：下午 6:02",item:"2 × 加州卷",note:"不要芝麻",thanks:"底部文字",save:"保存模板",saved:"小票模板已保存。新订单将使用此模板。",loading:"加载中…",error:"无法加载或保存小票模板。",denied:"您需要此门店的位置设置权限。",auth:"请重新登录。",invalid:"请检查模板内容后重试。",
};
const ko: typeof en = {
  eyebrow:"프린터 설정",title:"영수증 템플릿",description:"매장별 영수증 모양과 표시할 주문 정보를 설정합니다. 새 결제 주문부터 저장된 템플릿을 사용합니다.",location:"매장",chooseLocation:"매장 선택",appearance:"모양",header:"상단 문구",headerPlaceholder:"선택 사항인 매장 또는 주방 제목",footer:"하단 문구",footerPlaceholder:"선택 사항인 하단 메시지",fontSize:"글자 크기",compact:"작게",standard:"표준",large:"크게",complete:"전체 주문 영수증",station:"스테이션 영수증",customerPhone:"고객 전화번호",placedTime:"주문 시간",itemPrices:"메뉴 가격",subtotal:"소계",discount:"할인",tax:"세금",tip:"팁",orderTotal:"전체 주문 합계",stationCount:"스테이션 메뉴 수량",preview:"미리보기",previewHelp:"미리보기에는 선택한 항목이 표시됩니다. 실제 줄바꿈은 메뉴 이름에 따라 달라질 수 있습니다.",order:"픽업 · 전체 주문",stationOrder:"픽업 · 스시 바",customer:"Alex Chen",phone:"416-555-0123",pickup:"픽업: 오후 6:30",placed:"주문: 오후 6:02",item:"2 × 캘리포니아 롤",note:"참깨 빼기",thanks:"하단 문구",save:"템플릿 저장",saved:"영수증 템플릿을 저장했습니다. 새 주문부터 적용됩니다.",loading:"불러오는 중…",error:"영수증 템플릿을 불러오거나 저장할 수 없습니다.",denied:"이 매장의 위치 설정 권한이 필요합니다.",auth:"다시 로그인하세요.",invalid:"템플릿 내용을 확인하고 다시 시도하세요.",
};

export const receiptTemplateTranslations: Record<Locale, typeof en> = { en, zh, ko };
