export type SystemMenuDto = {
  id: string | null;
  parentId: string | null;
  name: string;
  description?: string | null;
  nameEn?: string | null;
  nameZh?: string | null;
  nameKo?: string | null;
  descriptionEn?: string | null;
  descriptionZh?: string | null;
  descriptionKo?: string | null;
  code: string;
  path: string | null;
  component: string | null;
  icon: string | null;
  menuType: string;
  sortOrder: number | null;
  isVisible: boolean | null;
  isEnabled: boolean | null;
  createdAt: string | null;
  updatedAt: string | null;
};

export type SystemMenuUpsertRequest = {
  parentId: string | null;
  name: string;
  nameEn?: string | null;
  nameZh?: string | null;
  nameKo?: string | null;
  descriptionEn?: string | null;
  descriptionZh?: string | null;
  descriptionKo?: string | null;
  code: string;
  path: string | null;
  component: string | null;
  icon: string | null;
  menuType: string;
  sortOrder: number | null;
  isVisible: boolean;
  isEnabled: boolean;
};
